const EMAILJS_PUBLIC_KEY = "TU_PUBLIC_KEY";
const EMAILJS_SERVICE_ID = "TU_SERVICE_ID";
const EMAILJS_TEMPLATE_ID = "TU_TEMPLATE_ID";
let compras = [];
function initCompras(){requireSession(); compraFecha.value=new Date().toISOString().slice(0,10); compras=DB.get("compras",[]); cargarProductosCompra(); purchaseForm.addEventListener("submit",guardarCompra); compraCantidad.addEventListener("input",actualizarTotalCompra); compraPrecio.addEventListener("input",actualizarTotalCompra); renderCompras(); if(window.emailjs && EMAILJS_PUBLIC_KEY !== "TU_PUBLIC_KEY") emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});}
function cargarProductosCompra(){const productos=DB.get("productos",[]); compraProducto.innerHTML='<option value="">Seleccione un producto</option>'+productos.map(p=>`<option value="${p.id}">${esc(p.nombre)} · Stock: ${p.stock}</option>`).join("");}
function actualizarTotalCompra(){compraTotal.textContent=money(Number(compraCantidad.value)*Number(compraPrecio.value));}
async function guardarCompra(e){e.preventDefault();const productos=DB.get("productos",[]);const producto=productos.find(p=>p.id===compraProducto.value);const cantidad=Number(compraCantidad.value);const precio=Number(compraPrecio.value);if(!producto)return alert("Seleccione un producto.");if(cantidad<=0||precio<0)return alert("Cantidad o precio inválido.");producto.stock+=cantidad;const total=cantidad*precio;const compra={id:uid(),fecha:compraFecha.value,proveedor:compraProveedor.value.trim(),productoId:producto.id,producto:producto.nombre,cantidad,precio,total,correo:correoCompra.value.trim()};compras.unshift(compra);DB.set("productos",productos);DB.set("compras",compras);registrarMovimiento("ENTRADA",producto.nombre,cantidad,`Compra a ${compra.proveedor}`);await enviarCorreo(compra);purchaseForm.reset();compraFecha.value=new Date().toISOString().slice(0,10);cargarProductosCompra();renderCompras();alert("Compra registrada y stock actualizado.");}
async function enviarCorreo(compra){if(!window.emailjs||EMAILJS_PUBLIC_KEY==="TU_PUBLIC_KEY"){console.info("EmailJS no configurado. Complete las credenciales en compras.js.");return;}try{await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,{to_email:compra.correo,fecha:compra.fecha,proveedor:compra.proveedor,producto:compra.producto,cantidad:compra.cantidad,total:money(compra.total)});}catch(error){console.error("Error enviando correo:",error);alert("La compra se registró, pero el correo no pudo enviarse. Revise la configuración de EmailJS.");}}
function renderCompras(){purchaseBody.innerHTML=compras.map(c=>`<tr><td>${esc(c.fecha)}</td><td>${esc(c.proveedor)}</td><td>${esc(c.producto)}</td><td>${c.cantidad}</td><td>${money(c.total)}</td><td>${esc(c.correo)}</td></tr>`).join("");purchaseEmpty.style.display=compras.length?"none":"block";}
document.addEventListener("DOMContentLoaded",initCompras);
